var _bmp_format_8h =
[
    [ "tagBITMAPCOREHEADER", "structtag_b_i_t_m_a_p_c_o_r_e_h_e_a_d_e_r.html", "structtag_b_i_t_m_a_p_c_o_r_e_h_e_a_d_e_r" ],
    [ "tagBITMAPINFOHEADER", "structtag_b_i_t_m_a_p_i_n_f_o_h_e_a_d_e_r.html", "structtag_b_i_t_m_a_p_i_n_f_o_h_e_a_d_e_r" ],
    [ "tagBITMAPV4HEADER", "structtag_b_i_t_m_a_p_v4_h_e_a_d_e_r.html", null ],
    [ "tagBITMAPV5HEADER", "structtag_b_i_t_m_a_p_v5_h_e_a_d_e_r.html", null ],
    [ "tagBITMAPHEADER", "structtag_b_i_t_m_a_p_h_e_a_d_e_r.html", "structtag_b_i_t_m_a_p_h_e_a_d_e_r" ],
    [ "tagBITMAPHEADER::tagBITMAPHEADERS", "uniontag_b_i_t_m_a_p_h_e_a_d_e_r_1_1tag_b_i_t_m_a_p_h_e_a_d_e_r_s.html", "uniontag_b_i_t_m_a_p_h_e_a_d_e_r_1_1tag_b_i_t_m_a_p_h_e_a_d_e_r_s" ],
    [ "tagBITMAPBITFIELD", "structtag_b_i_t_m_a_p_b_i_t_f_i_e_l_d.html", "structtag_b_i_t_m_a_p_b_i_t_f_i_e_l_d" ],
    [ "tagRGBTRIPLE", "structtag_r_g_b_t_r_i_p_l_e.html", "structtag_r_g_b_t_r_i_p_l_e" ],
    [ "tagRGBQUAD", "structtag_r_g_b_q_u_a_d.html", "structtag_r_g_b_q_u_a_d" ],
    [ "tagBITMAPCOLORPALETTE", "structtag_b_i_t_m_a_p_c_o_l_o_r_p_a_l_e_t_t_e.html", "structtag_b_i_t_m_a_p_c_o_l_o_r_p_a_l_e_t_t_e" ],
    [ "tagBITMAPCOLORPALETTE::tagBITMAPCOLORPALETTES", "uniontag_b_i_t_m_a_p_c_o_l_o_r_p_a_l_e_t_t_e_1_1tag_b_i_t_m_a_p_c_o_l_o_r_p_a_l_e_t_t_e_s.html", "uniontag_b_i_t_m_a_p_c_o_l_o_r_p_a_l_e_t_t_e_1_1tag_b_i_t_m_a_p_c_o_l_o_r_p_a_l_e_t_t_e_s" ],
    [ "tagBITMAPFILEHEADER", "structtag_b_i_t_m_a_p_f_i_l_e_h_e_a_d_e_r.html", "structtag_b_i_t_m_a_p_f_i_l_e_h_e_a_d_e_r" ],
    [ "BITMAPBITFIELD", "_bmp_format_8h.html#aa4a84b04cdb0f92ab2ac5e814b8d50b0", null ],
    [ "BITMAPCOLORPALETTE", "_bmp_format_8h.html#ad0cdbe4068c50a72b549c16ea30ab42d", null ],
    [ "BITMAPCOREHEADER", "_bmp_format_8h.html#a4abdac5d670e69a04179c429c536d6d8", null ],
    [ "BITMAPFILEHEADER", "_bmp_format_8h.html#a207168d0a197298edddf25384c8de685", null ],
    [ "BITMAPHEADER", "_bmp_format_8h.html#ad4a4063255ea340c97992d2748fdb193", null ],
    [ "BITMAPINFOHEADER", "_bmp_format_8h.html#a463da1a36c110a831b0d7cefbd9730be", null ],
    [ "BITMAPV4HEADER", "_bmp_format_8h.html#aa63554a8e06209075ed28f1d3f875fe2", null ],
    [ "BITMAPV5HEADER", "_bmp_format_8h.html#af8574cc566cce50f33e9a9c78cc8a7f8", null ],
    [ "RGBQUAD", "_bmp_format_8h.html#a5300ccf6ce90d06ab13492604c8581c4", null ],
    [ "RGBTRIPLE", "_bmp_format_8h.html#a3605ad6365cca66c4ad8d4391374cd6d", null ]
];